#!/bin/sh

if [ "$1" == "" ]; then
   echo "Usage: $0 <directory>"
   exit 1
fi

DIRE=$1
#cmsenv
OUTPUT=$DIRE/Log/LastFile
OLDFILE='nn'

while /bin/true ; do

  FILE=`./lastSpyMode $DIRE`
  #echo $FILE vs $OLDFILE
  if [ "$FILE" != "$OLDFILE" ] ; then
    echo New file available
    echo "$FILE"> $OUTPUT 
  fi
  sleep 5 

  OLDFILE=$FILE
done
